#' Load raw inventory data and make them ready for CLCC calculation
#'
#' This function loads raw inventory data as xlsx files generated by the LCA SimaPro
#' software. The function loads all the inventories in a given folder: the file name becomes
#' the name of the object to be evaluated. The function also converts raw data to measurement
#' units compatible with those of reference prices.
#' Land use changes, at the moment, are not considered while computing the indicator and therefore the
#' `land_use` parameter is set to `FALSE`. Future versions of the CLCC indicator might include this
#' dimension as well.
#'
#' @param data_path A character string. Path to the folder in which raw xlsx files are stored.
#'     File names will be used as object names on which computing the CLCC indicator.
#' @param land_use A logical value. If `TRUE`, land use change are evaluated otherwise they are
#'     excluded from the analysis. Default is set to `FALSE`.
#' @return A tidy dataset with inventory data organized by object
inventory_load_fn <- function(data_path, land_use = FALSE){

comm <- file_path <- inventory_raw <- data <- object <- no <- um <-
  um_to <- quantity <- comp <- no_comm <- phase <- NULL # avoids notes (dplyr and NSE)

if (!is.logical(land_use)) stop("The land_use parameter can only assume TRUE or FALSE values")

file_list <- list.files(path = data_path,
                            full.names = TRUE,
                            recursive = TRUE,
                            pattern = "*.xlsx") # creates a vector with variable names

inventory_raw <- tidyr::tibble(file_path = file_list) # creates a tibble

# identifying the number of rows to skip in each excel file

inventory_raw$skip <- purrr::map_dbl(inventory_raw$file_path, start_data_finder_fn)

# loading inventory data
inventory_raw <- inventory_raw %>%
  dplyr::rowwise() %>%
  dplyr::mutate(data = purrr::map(file_path, readxl::read_excel, skip = skip)) %>%
  dplyr::ungroup()

inventory_raw <- within(inventory_raw, {
  object <- stringr::str_remove(file_path, paste0(here::here(data_path), "/"))
  object <- stringr::str_remove(object, ".xlsx")
  file_path <- NULL
  skip <- NULL
})

# renaming the first 5 variables of each inventory

inventory_raw <- inventory_raw %>%
  dplyr::mutate(data = purrr::map(data,
                                  function(x){
                                    x %>%
                                    dplyr::rename(no = 1, comm = 2, comp = 3,
                                                  um = 4, total = 5) %>%
                                    dplyr::rename_all(tolower)
                                  }))

# tidying the dataset (grouping needed because of different number of phases across objects)

inventory_tidy <- inventory_raw %>%
  dplyr::mutate(data = purrr::map(data,
                                  function(x){
                                    tidyr::pivot_longer(x, !c(no:um),
                                    names_to = "phase", values_to = "quantity")
                                  })) %>%
  tidyr::unnest(data)

# loading data on measurement units

meas_units <- subset(clccr::clcc_prices_ref,
                     select = c(comm, no_comm, um))

meas_units <- within(meas_units, {
  um_to <- um
  um <- NULL
})

# filtering data (raw materials only, belonging to the list of materials for which prices are avilable)

# commodities to be considered ####
comm_names <- unique(clccr::clcc_prices_ref$comm)

inventory_tidy <- subset(inventory_tidy,
                         comp %in% c("Prima", "Raw") & comm %in% comm_names)

# converting measurement units

inventory_tidy <- merge(inventory_tidy, meas_units, all.x = TRUE)

inventory_tidy$um <- ifelse(inventory_tidy$um == paste0("\u00b5", "g"), "ug", # \u00b5" unicode character for mu
                                inventory_tidy$um) # micrograms are expressed wit "ug" in the udunits2 package

if (isFALSE(land_use)) {

inventory_tidy <- inventory_tidy[!inventory_tidy$um %in% c("m2a", "m2", "m3y"), ]

}

inventory_tidy <- inventory_tidy %>%
  dplyr::rowwise() %>%
  dplyr::mutate(quantity = um_converter( # converting measurement units if needed
    quantity, um, um_to
  )) %>%
  dplyr::ungroup()

tidyr::as_tibble(inventory_tidy[, -which(names(inventory_tidy) %in% c("no", "comp", "um_to"))])


}
