#' Load raw inventory data and make them ready for CLCC calculation
#'
#' This function loads raw inventory data as xlsx files generated by the LCA SimaPro
#' software. The function loads all the inventories in a given folder: the file name becomes
#' the name of the object to be evaluated. The function also converts raw data to measurement
#' units compatible with those of reference prices.
#' This function can optionally load also critical weights from an Excel file. Such weights are project-specific.
#' Some materials are considered critical by the European Commission of the International Energy Agency (IEA) but are not considered as individual flows by
#' SimaPro. For example the SimaPro flow "Coal, hard" contains "coking coal" which is critical. The weights are therefore needed to
#' compute the Critical-CLCC indicators.
#'
#' @param data_path A character string. Path to the folder in which raw xlsx files are stored.
#'      File names will be used as object names on which computing the CLCC indicator.
#' @param use_weights A logical value. If set to `TRUE`, the function uses the critical weights
#' @param weights_path A character vector. Path to the file containing the critical weights for each commodity and phase.
#' @return A tidy dataset with inventory data organized by object
#' @export
inventory_load_fn <- function(
    data_path,
    use_weights = FALSE,
    weights_path
){

  comm <- file_path <- inventory_raw <- data <- object <- no <- um <-
    um_to <- quantity <- comp <- no_comm <- phase <- NULL

  file_list <- list.files(path = data_path,
                          full.names = TRUE,
                          recursive = TRUE,
                          pattern = "*.xlsx")

  inventory_raw <- tidyr::tibble(file_path = file_list)

  inventory_raw$skip <- purrr::map_dbl(inventory_raw$file_path, start_data_finder_fn)

  inventory_raw <- inventory_raw |>
    dplyr::rowwise() |>
    dplyr::mutate(data = purrr::map(file_path, function(file, skip) {
      num_cols <- ncol(readxl::read_excel(file, skip = skip, n_max = 1))
      col_types_vec <- c(rep("guess", 4), rep("text", num_cols - 4))
      readxl::read_excel(file, skip = skip, col_types = col_types_vec)
    }, skip = skip)) |>
    dplyr::ungroup()

  inventory_raw <- within(inventory_raw, {
    object <- stringr::str_remove(file_path, paste0(data_path, "/"))
    object <- stringr::str_remove(object, ".xlsx")
    file_path <- NULL
    skip <- NULL
  })

  inventory_raw <- inventory_raw |>
    dplyr::mutate(data = purrr::map(data, ~ {
      .x <- .x |>
        dplyr::rename(no = 1, comm = 2, comp = 3, um = 4, total = 5)

      .x <- .x |>
        dplyr::mutate(dplyr::across(5:ncol(.x), ~as.numeric(gsub(",", ".", .))))

      return(.x)
    }))

  inventory_tidy <- inventory_raw |>
    dplyr::mutate(data = purrr::map(data,
                                    function(x){
                                      tidyr::pivot_longer(x, !c(no:um),
                                                          names_to = "phase", values_to = "quantity")
                                    })) |>
    tidyr::unnest(data)

  meas_units <- clccr::clcc_prices_ref |>
    dplyr::select(comm, no_comm, um) |>
    dplyr::distinct() |>
    dplyr::mutate(comm = tolower(comm))

  meas_units <- within(meas_units, {
    um_to <- um
    um <- NULL
  })

  comm_names <- unique(tolower(clccr::clcc_prices_ref$comm))

  inventory_tidy <- inventory_tidy |>
    dplyr::mutate(comm = tolower(comm)) |>
    dplyr::filter(comp %in% c("Prima", "Raw") & comm %in% comm_names)

  inventory_tidy <- inventory_tidy |>
    dplyr::left_join(meas_units, by = "comm")

  inventory_tidy$um <- ifelse(inventory_tidy$um == paste0("\u00b5", "g"), "ug", inventory_tidy$um)
  inventory_tidy$no <- NULL

  inventory_tidy <- inventory_tidy[!inventory_tidy$um %in% c("m2a", "m2", "m3y", "MJ"), ]

  inventories <- inventory_tidy |>
    dplyr::mutate(dplyr::across(dplyr::where(is.character), tolower))

  # Loading critical weights
  if (use_weights){
    if (is.null(weights_path)) {
      stop("If 'use_weights' is TRUE, 'weights_path' cannot be NULL, please specify a valid path to the weight table")
    } else {
      critical_weights <- critical_weights_load_fn(weights_path = weights_path)

      if (!identical(unique(critical_weights$coke$object), unique(critical_weights$silicon$object)))
        warning("The objects in the coke and the silicon weight tibbles are not the same, please check")

      if (!identical(unique(critical_weights$coke$phase), unique(critical_weights$silicon$phase)))
        warning("The phases in the coke and the silicon weight tibbles are not the same, please check")

      inventory_objects <- sort(unique(inventories$object))

      weights_objects <- purrr::map(
        names(critical_weights),
        \(x) sort(unique(critical_weights[[x]][["object"]]))
      ) |> stats::setNames(names(critical_weights))

      if(!identical(sort(unique(critical_weights$coke$object)), sort(unique(critical_weights$silicon$object))))
        stop("Objects in the critical weights for coke and silicon do not match. Please check the weight files")

      for (x in c("coke", "silicon")) {
        if(length(inventory_objects) > length(critical_weights[[x]][["object"]]))
          stop(paste0(stringr::str_to_sentence(x),
                      " critical weights for one or more objects are missing, please check the files"))

        if(length(intersect(inventory_objects, critical_weights[[x]][["object"]])) == 0)
          stop(paste0("The inventory and ", x, " critical weights files contain completely different objects. Check the files"))

        if(length(inventory_objects) < length(unique(critical_weights[[x]][["object"]])))
          warning(paste0("Not all the objects in the ", x, " critical weights file are present in the inventories. Those not present have been removed"))
      }

      critical_weights <- purrr::map(
        critical_weights,
        \(x) dplyr::filter(x, .data[["object"]] %in% inventory_objects)
      ) |> stats::setNames(names(critical_weights))

      critical_weights <- purrr::map(
        names(critical_weights),
        \(x){
          if(x == "coke"){
            dplyr::rename(critical_weights[[x]], "weight" = "value")
          } else if (x == "silicon"){
            dplyr::rename(critical_weights[[x]], "quantity" = "value")
          }
        }
      ) |> stats::setNames(names(critical_weights))

      col_to_add_v <- setdiff(colnames(inventories), colnames(critical_weights$silicon))

      col_to_add_v <- inventories |>
        dplyr::filter(comm == "silicon") |>
        dplyr::select(dplyr::all_of(col_to_add_v)) |>
        unique() |>
        dplyr::mutate(dplyr::across(dplyr::everything(), as.character)) |>
        tidyr::pivot_longer(dplyr::everything(), names_to = "var_names", values_to = "var_values") |>
        tibble::deframe()

      new_data_silicon <- critical_weights$silicon |>
        dplyr::mutate(!!!col_to_add_v) |>
        dplyr::mutate(no_comm = as.numeric(.data[["no_comm"]]),
                      comm = ifelse(comm == "silicon mg", "silicon", .data[["comm"]]))

      inventories <- inventories |>
        dplyr::bind_rows(new_data_silicon) |>
        dplyr::group_by(.data[["object"]], .data[["comm"]], .data[["phase"]], .data[["comp"]], .data[["um"]],
                        .data[["no_comm"]], .data[["um_to"]]) |>
        dplyr::summarise(quantity = sum(quantity, na.rm = TRUE), .groups = "drop") |>
        dplyr::left_join(critical_weights$coke, by = c("object", "phase", "comm"))

      inventories$weight <- ifelse(is.na(inventories$weight), 1, inventories$weight)
    }
  } else {
    inventories$weight <- 1
  }

  return(inventories)
}
